.eslintrc.js
.prettierrc
.vscode/setting.json
package.json
yarn.lock

- **closed #8** 
- ESlint, Prettier 설정했습니다.
이제 파일 저장 시, ESlint 규칙에 따라 코드가 수정되고, Prettier 설정에 따라 코드가 포맷팅됩니다.

[Feature] - ESlint & Prettier 설정했습니다. 

---

Dockerfile-front-prod

[BugFix] - 도커 파일 yarn install 수정했습니다.

---

src/components/pages/loginPage/loginPage.jsx

[Feature] - 소셜로그인 연결 중입니다.

---

package.json

[Feature] - 소셜 로그인 구현 중입니다.

---

package.json
src/components/pages/loginPage/constants/index.js
src/components/pages/loginPage/utils/apiUtil.js
src/router/allRouter.js
yarn.lock

- closed #33 
- jwt 토큰이 존재하는지 확인하는 로직 구현
- 만약 토큰이 존재하지 않을 경우 로그인 페이지로 리다이렉트

[Feature] - jwt 토큰 유무 로직 구현했습니다.

---

package.json
src/asset/sass/etc/tabBar/tabBar.scss
src/components/global/token/tokenManagement.jsx
src/router/allRouter.js
yarn.lock

- closed #34 
- 토큰 수신 확인 로직 구현했습니다
- 토큰이 제대로 수신 되었다면, login/userinfo 페이지로 리다이렉트 됩니다.

[Feature] - 토큰 수신 확인 로직 구현했습니다.

---

src/router/allRouter.js

[Feature] - 라우터 오류 해결했습니다.

---

src/asset/sass/etc/tabBar/tabBar.scss
src/router/allRouter.js

[Feature] - 로그인, 메인 페이지 오류 해결했습니다.

---

README.md

[Feature] - Readme 수정

---

README.md

[Feature] - 라우터 오류 수정했습니다.

---

src/components/global/token/tokenManagement.jsx

- closed #36 
- 토큰 디코딩 로직 변경했습니다.

[Feature] - 토큰 디코딩 로직 변경했습니다.

---

src/router/allRouter.js

#57 
- 로그인 과정 중, 회원일 때 보던 페이지로 리다이렉트 하는 부분 수정했습니다.

[BugFix] - 로그인 페이지 Redirect 오류 수정했습니다.

---

src/components/global/utils/apiUtil.js
src/components/pages/loginPage/constants/index.js
src/components/pages/loginPage/nicknamePage.jsx

- #57 
- fetch  POST 요청 url 변경했습니다.

[BugFix] - fetch url 변경했습니다.

---

src/components/global/utils/apiUtil.js
src/components/pages/loginPage/constants/index.js
src/components/pages/loginPage/nicknamePage.jsx
src/router/allRouter.js

- #57 
- fetch  POST 요청 url 변경했습니다.

운영 서버에 배포합니다.

---

src/components/pages/loginPage/nicknamePage.jsx

- #57 
- fetch api url 수정했습니다.
- 데이터 전송된 후, 시작하기 버튼 눌렀을 때 메인페이지로 리다이렉트 됩니다.

[BugFix] - api url 수정했습니다.

---

package.json
src/asset/image/loginuser.svg
src/asset/sass/etc/header/header.scss
src/components/pages/loginPage/nicknamePage.jsx
src/components/ui/ageSelection/ageSelection.jsx
src/components/ui/ageSelection/ageSelection.scss
src/components/ui/genderSelection/genderSelection.jsx
src/components/ui/genderSelection/genderSelection.scss
src/components/ui/header/header.jsx
yarn.lock

- #64 
- 태그에 호버 시, 색 변경
- 태그 두 번 눌렀을 때 취소
- 로그인 성공하고, 메인으로 돌아갔을 때, user.svg 파일로 변경 -> 테스트 필요
- 체크 버튼 선택 시, 시작하기 버튼 색 변경
- useHistory에서 useNavigation으로 변경

[Feature] - 로그인 전체 과정 체크합니다.

---

package.json
src/components/pages/loginPage/nicknamePage.jsx
src/components/pages/mainPage/mainPage.jsx
yarn.lock

- closed #36 
- 토큰 전송 헤더 수정했습니다.

[BugFix] - 토큰 전송 헤더 수정했습니다.

---

package.json
src/components/global/token/tokenManagement.jsx
src/components/global/utils/apiUtil.js
src/components/pages/loginPage/loginPage.jsx
src/components/pages/loginPage/nicknamePage.jsx
src/components/ui/header/header.jsx

- closed #64 
- 태그에 호버를 올렸을 경우 색이 변경되도록 수정했습니다.
- 태그를 한 번 더 클릭했을 경우 태그 버튼이 해제되도록 설정했습니다.
- 로그인에 성공 시, 메인 화면에 로그인/가입 버튼이 아닌 usericon으로 변경하도록 수정했고, 로그인 유저일 경우 로그인 페이지에 진입할 수 없도록 막았습니다. 
- 정보 등록 페이지에서 시작하기 버튼을 눌렀을 때, 나이, 성별, 태그, 로그인 유무 정보가 서버로 전송되고, 토큰과 태그 정보는 로컬 스토리지에 저장되도록 했습니다.
- 태그 데이터 이동 시, 각 버튼에 따라 "취준생" , "현직자"로 가도록 설정했습니다.

[Feature] - 로그인 전 과정 수정했습니다.

---

src/components/global/utils/apiUtil.js
src/components/pages/loginPage/constants/index.js
src/components/ui/header/header.jsx

[BugFix] - index.js 변수명 수정했습니다.

---

src/components/global/utils/apiUtil.js
src/components/pages/loginPage/loginPage.jsx

- #72 
- 메인에서도 토큰 확인 로직이 실행돼서 메인부터 접근이 막히는 오류 해결

[BugFix] - 토큰 확인 로직 수정했습니다.

---

src/components/ui/header/header.jsx

- #72 
- 로그인 여부 확인하는 방식 변경했습니다.

[BugFix] - 로그인 여부 확인하는 방식 변경했습니다.

---

package.json
src/asset/sass/etc/header/header.scss
src/components/pages/myPage/myPage.jsx
src/components/pages/notificationPage/notificationPage.jsx
src/components/ui/header/header.jsx
src/router/allRouter.js

- #79 
마이페이지 -> 로그인 성공 시, 열림
알림페이지 -> 로그인 성공 시, 열림
유저 아이콘 배경색 지우고, 위치 조정
유저 아이콘 클릭 시, 마이페이지 연결
마이페이지에 간단한 로그아웃 버튼 만들어서 로그아웃 구현

[Feature] - 로그인과 연결되는 페이지 로직 수정했습니다.

---

package.json
src/asset/image/loginuser.svg
src/asset/sass/etc/header/header.scss
src/components/pages/loginPage/loginPage.jsx
src/components/pages/myPage/myPage.jsx
src/components/pages/storePage/storePage.jsx
src/components/ui/header/header.jsx
src/router/allRouter.js

- #83
- 헤더 UI 수정 및 로직 구현
- 로그아웃 로직 수정했습니다.

[Feature] - 메인 헤더, 로그아웃 버튼 로직 수정했습니다

---

src/asset/sass/pages/myPage/myPage.scss
src/components/pages/myPage/myPage.jsx

- className이 겹쳐 UI가 엇갈렸습니다.
ㄴ className ( bun-count -> mypage-bun-count ) 로 변경했습니다.

[Bugfix] className 수정

---

src/components/pages/searchPage/searchPage.jsx
src/router/allRouter.js

- #94
-  콘솔 입력 및 라우터 토큰 주석 처리 했습니다

[BugFix] 콘솔 입력 및 라우터 토큰 주석 처리

---

src/asset/sass/etc/header/userInfoHeader.scss
src/components/global/token/tokenManagement.jsx
src/components/pages/loginPage/nicknamePage.jsx
src/components/pages/notificationPage/notificationPage.jsx
src/components/pages/searchPage/companyRegistPage.jsx
src/components/pages/searchPage/searchPage.jsx
src/components/pages/searchPage/searchResultPage.jsx
src/components/ui/header/titleHeader.jsx
src/components/ui/header/userInfoHeader.jsx

- 자동완성 API 로직 수정 했습니다.
- 그 외 자잘한 로직 오류 수정했습니다.

[BugFix] API 로직 수정했습니다.

---

src/asset/sass/etc/header/userInfoHeader.scss
src/components/ui/header/userInfoHeader.jsx
src/router/allRouter.js

[Bugfix] 오류 코드 수정했습니다.

---

package.json
src/asset/sass/etc/question/question.scss
src/asset/sass/pages/mainPage/mainPage.scss
src/asset/sass/pages/postPage/questionWritePage.scss
src/components/pages/mainPage/mainPage.jsx
src/components/pages/postPage/questionDetailPage.jsx
src/components/pages/postPage/questionWritePage.jsx
src/components/pages/searchPage/companyInfoPage.jsx
src/components/pages/searchPage/searchResultPage.jsx
src/components/ui/question/question.jsx
src/components/ui/searchInput/searchInput.jsx

- #103 
- 기업 목록 페이지 
- 기업 상세보기 페이지
- 기업 정보 등록 페이지
- 질문 등록 페이지
- 질문 상세보기 페이지
API 연결했습니다 -

[Feature] 검색 - 기업 목록 - 질문 - 질문 등록 페이지 API 연결

---

src/components/pages/searchPage/companyRegistPage.jsx
src/components/pages/searchPage/searchResultPage.jsx

[BugFix] API 로직 오류 수정

---

src/components/pages/searchPage/searchResultPage.jsx

[Bugfix] API 키값 수정했습니다. 

---

src/components/pages/searchPage/searchResultPage.jsx

[BugFix] API 로직 수정

---

src/components/pages/searchPage/searchResultPage.jsx
src/components/ui/searchInput/searchInput.jsx

fix: 검색 수정 중입니다.

---

src/components/pages/searchPage/searchResultPage.jsx

fix: useLocation 추가했습니다.

---

src/components/pages/searchPage/searchResultPage.jsx
src/components/ui/searchInput/searchInput.jsx

fix: 검색 수정합니다.

---

src/components/pages/searchPage/companyRegistPage.jsx
src/index.js

- #115 
- 기업 등록 API 주소 수정
- 기업 등록 후 리다이렉트 주소 수정

[Bugfix] 기업 등록 페이지 수정

---

src/components/pages/searchPage/companyRegistPage.jsx

[Bugfix] 기업 등록 페이지 내 토큰 제거했습니다.

---

src/components/pages/postPage/questionWritePage.jsx
src/components/pages/searchPage/companyInfoPage.jsx
src/components/pages/searchPage/companyRegistPage.jsx

[Bugfix] API 연결 로직 수정했습니다.

---

package.json
src/router/allRouter.js

개발 서버에 배포합니다.

---

src/components/pages/myPage/myPage.jsx
src/components/pages/myPage/secessionPage.jsx
src/components/pages/postPage/questionDetailPage.jsx
src/components/pages/postPage/questionWritePage.jsx
yarn.lock

[Feature] 답변, 회원탈퇴 api 로직 수정했습니다. 

---

src/components/pages/myPage/infoEditPage.jsx
src/components/pages/myPage/secessionPage.jsx
src/globalStyles.js
src/styledComponent.js

[Bugfix] 닉네임 변경, 회원탈퇴 로직 수정했습니다.

---

src/asset/sass/etc/header/userInfoHeader.scss
src/asset/sass/etc/question/question.scss
src/asset/sass/pages/mainPage/mainPage.scss
src/components/pages/mainPage/mainPage.jsx
src/components/pages/myPage/infoEditPage.jsx
src/components/pages/myPage/myPage.jsx
src/components/pages/myPage/secessionPage.jsx
src/globalStyles.js
src/styledComponent.js

[Bugfix] API 테스트 중입니다.

---

src/components/pages/myPage/infoEditPage.jsx

API 테스트 중입니다.

---

package.json
src/asset/image/questitle.svg
src/asset/image/report.svg
src/asset/sass/etc/question/question.scss
src/asset/sass/etc/selection/fishTag.scss
src/asset/sass/etc/selection/secessionSelection.scss
src/asset/sass/pages/adminPage/adminMainPage.scss
src/asset/sass/pages/myPage/infoEditPage.scss
src/asset/sass/pages/myPage/myPage.scss
src/asset/sass/pages/myPage/secessionPage.scss
src/asset/sass/pages/postPage/questionDetailPage.scss
src/asset/sass/pages/postPage/questionWritePage.scss
src/asset/sass/pages/searchPage/companyInfoPage.scss
src/asset/sass/pages/searchPage/searchResultPage.scss
src/components/pages/adminPage/adminMainPage.jsx
src/components/pages/myPage/infoEditPage.jsx
src/components/pages/myPage/myPage.jsx
src/components/pages/myPage/secessionPage.jsx
src/components/pages/postPage/questionDetailPage.jsx
src/components/pages/postPage/questionWritePage.jsx
src/components/pages/searchPage/companyInfoPage.jsx
src/components/ui/question/answer.jsx
src/components/ui/question/question.jsx
src/components/ui/selection/fishTag.jsx
src/components/ui/selection/secessionSelection.jsx
src/router/allRouter.js

[Feature] 페이지 UI 구현 및 수정 중입니다.

---

package.json
src/asset/sass/pages/notificationPage/notificationList.scss
src/asset/sass/pages/notificationPage/notificationPage.scss
src/components/pages/notificationPage/notificationList.jsx
src/components/pages/notificationPage/notificationPage.jsx
src/globalStyles.js
src/router/allRouter.js
src/styledComponent.js

[Fix] set에서 export로 수정했습니다

---

package.json
src/asset/sass/pages/myPage/noticePage.scss
src/components/pages/myPage/noticePage.jsx
src/globalStyles.js
src/styledComponent.js

closed #134 
공지사항 리스트 토글 및 페이지네이션 구현했습니다.
https://github.com/COFLLL/CoverFlow-FE/assets/88266129/62fda968-d542-4091-abaf-9ebfc8167ef2

Feature/notice page UI

---

package.json
src/components/global/constants/index.js
src/components/pages/loginPage/nicknamePage.jsx
src/components/ui/contactSlider/contactList.jsx
src/components/ui/contactSlider/contactList.scss
src/components/ui/contactSlider/contactSlider.jsx
src/components/ui/contactSlider/contactSlider.scss

#143 
- 문의 하기 페이지 내 문의 작성 연결
- 문의 하기 페이지 내 문의 내역 조회 연결
- 1차 테스트 이후 react query로 재구성

[Feature] 문의 페이지 API 연결했습니다. 

---

package.json
src/components/pages/myPage/infoEditPage.jsx
src/components/pages/myPage/myPage.jsx
src/components/pages/postPage/questionDetailPage.jsx
src/components/pages/postPage/questionWritePage.jsx
src/components/pages/searchPage/companyInfoPage.jsx
src/components/pages/searchPage/companyRegistPage.jsx
src/components/pages/searchPage/searchResultPage.jsx
src/components/ui/header/userInfoHeader.jsx
src/components/ui/question/answerContainer.jsx
src/components/ui/searchInput/searchInput.jsx

#147
- 변경된 API 주소 적용했습니다.
- 문법으로 인한 ESLint 경고가 뜨는 부분 추가 수정했습니다.

[Bugfix] API 주소 수정

---

src/components/global/utils/apiUtil.js
src/components/pages/loginPage/nicknamePage.jsx
src/components/pages/myPage/infoEditPage.jsx
src/components/pages/myPage/myPage.jsx
src/components/pages/postPage/questionWritePage.jsx
src/components/pages/searchPage/companyRegistPage.jsx
src/components/pages/searchPage/searchResultPage.jsx
src/components/ui/contactSlider/contactSlider.jsx
src/components/ui/header/userInfoHeader.jsx
src/components/ui/searchInput/searchInput.jsx

 [BugFix] - 변경된 API 주소 확인

---

src/asset/sass/pages/myPage/premiumPage.scss
src/components/pages/premiumPage/premiumTicket.jsx
src/router/allRouter.js

#138
프리미엄 페이지 내 태그 CSS 부분 수정했습니다.

[Feature] 공지사항 페이지 UI 구현했습니다.

---

src/components/ui/searchInput/searchInput.jsx
src/hooks/useDebounce.js

#151
- 검색 디바운스 적용
https://github.com/COFLLL/CoverFlow-FE/assets/88266129/8646f559-37b4-4fec-aa41-3a57eda1eb48

(COFLLL#151) feat : 검색 디바운스 적용했습니다.

---

src/asset/sass/pages/termsPage/termsPage.jsx
src/components/global/token/tokenManagement.jsx

[Bugfix] 토큰 받아오는 헤더 수정했습니다.

---

src/components/global/token/tokenManagement.jsx

#157
- 오류 해결과 테스트를 위한 콘솔 추가중입니다.

[hotfix] 토큰 받아오는 페이지 수정중입니다.

---

src/components/global/token/tokenManagement.jsx

[Bugfix] 토큰 로직 수정중입니다.

---

src/components/global/token/tokenManagement.jsx

[Bugfix] 토큰 로직 디버깅중입니다.

---

src/components/pages/postPage/questionWritePage.jsx
src/components/ui/selection/fishTag.jsx

*closed #172 
붕어빵 개수 반영 안되던 부분 수정

[Feature] 붕어빵 개수 반영

---

src/asset/sass/pages/myPage/noticePage.scss
src/asset/sass/pages/myPage/premiumPage.scss
src/asset/sass/pages/searchPage/companyInfoPage.scss
src/asset/sass/pages/searchPage/companyRegistPage.scss
src/components/pages/searchPage/searchResultPage.jsx
src/components/ui/searchInput/searchInput.jsx
src/utils/utils.js

#170
CSS및 로직 리팩토링 진행했습니다.
방향키로 검색 후 엔터 키 입력 시 검색 결과 안 나오는 부분은 수정 중입니다.

[Feature] CSS 및 로직 리팩토링

---

src/components/global/utils/apiUtil.js
src/components/ui/contactSlider/contactSlider.jsx

#167 
- 시간에 따른 리프레쉬 토큰 포함 여부를 결정하는api 훅 생성

[Feature] 리프레쉬 토큰 타이머 포함한 api 훅 테스트합니다.

---

src/components/global/utils/apiUtil.js
src/components/ui/contactSlider/contactSlider.jsx

[Bugfix] API 핸들러 수정합니다.

---

src/components/global/token/tokenManagement.jsx
src/components/global/utils/apiUtil.js

#166 
-  Redux  dispatch 로직 수정합니다.

[Bugfix] Redux  dispatch 로직 수정합니다.

---

src/components/global/token/tokenManagement.jsx
src/components/global/utils/apiUtil.js

#166
- Redux  dispatch 로직 수정합니다.

 [Bugfix] Redux  dispatch 로직 수정합니다.

---

src/asset/image/left_arrow.svg
src/asset/image/right_arrow.svg
src/components/global/utils/apiUtil.js
src/components/ui/contactSlider/contactList.jsx
src/components/ui/contactSlider/contactSlider.jsx

[Bugfix] API 요청 핸들러 수정합니다.

---

src/components/global/utils/apiUtil.js

[Bugfix] API 요청 헤더 수정합니다.

---

src/components/ui/contactSlider/contactList.jsx
src/components/ui/contactSlider/contactSlider.jsx

#166 
-  API 명세에 맞게 문의하기 내 코드 수정합니다.

[Bugfix] API 명세에 맞게 일부 코드 수정합니다.

---

src/components/global/utils/apiUtil.js
src/components/ui/contactSlider/contactList.jsx
src/components/ui/contactSlider/contactSlider.jsx

[Bugfix] - JSON 형식으로 인한 오류 수정합니다.

---

src/components/pages/myPage/noticePage.jsx
src/components/pages/searchPage/searchResultPage.jsx
src/components/ui/Pagination.jsx
src/components/ui/searchInput/searchInput.jsx

*closed #182
Pagination 컴포넌트 분리
API 변경으로 인한 로직 일부 수정

[UI] Pagination 컴포넌트 테스트 및 로직 수정

---

package.json
src/App.js
src/components/global/token/tokenManagement.jsx
src/components/global/utils/apiUtil.js
src/components/ui/contactSlider/contactList.jsx
src/components/ui/contactSlider/contactSlider.jsx
src/store/index.js
yarn.lock

#166 
- Redux 새로고침 시 데이터 유지 테스트합니다.

[Bugfix]Redux 새로고침 시 데이터 유지 테스트합니다.

---

src/asset/sass/etc/header/sideBar.scss

- closed #175 
- 사이드 바 음영이 넘치는 부분 수정했습니다.
- 푸터사라지게 하는 부분은 추후 추가하겠습니다!

[bugfix] 사이드 바 스타일 수정했습니다.

---

src/components/pages/loginPage/loginPage.jsx
src/components/pages/postPage/questionWritePage.jsx
src/components/ui/question/question.jsx

- 토스트 추가
- 데이터 프로퍼티 수정
- styled-components 이슈 수정
개선된 UI에 대한 반영사항은 추후 반영하겠습니다.

[Feat] 토스트 추가, 데이터 프로퍼티 수정, styled-components 관련 수정입니다.

---

src/components/pages/mainPage/mainPage.jsx

(COFLLL#195) feat : 실시간 알림 테스트입니다.

---

src/components/pages/postPage/questionDetailPage.jsx
src/components/pages/searchPage/companyInfoPage.jsx
src/components/pages/searchPage/searchResultPage.jsx

- API 변경으로 인한 데이퍼 프로퍼티 수정했습니다.

[Feature] 데이터 프로퍼티 변경 및 필요없는 코드 삭제

---

src/asset/sass/etc/inputBox/textArea.scss
src/asset/sass/etc/selection/fishTag.scss
src/asset/sass/pages/loginPage/loginPage.scss
src/asset/sass/pages/loginPage/nicknamePage.scss
src/asset/sass/pages/mainPage/mainPage.scss
src/asset/sass/pages/myPage/noticePage.scss
src/asset/sass/pages/postPage/questionWritePage.scss
src/asset/sass/pages/searchPage/companyRegistPage.scss
src/components/pages/loginPage/nicknamePage.jsx
src/components/pages/mainPage/mainPage.jsx
src/components/pages/postPage/questionWritePage.tsx
src/components/pages/searchPage/companyRegistPage.tsx
src/components/ui/Pagination.tsx
src/components/ui/genderSelection/genderSelection.jsx
src/components/ui/genderSelection/genderSelection.scss
src/components/ui/searchInput/searchInput.tsx
src/router/allRouter.js

[UI] 기업 등록 페이지 및 메인 페이지 UI 수정

---

src/components/pages/myPage/myPage.tsx
src/components/ui/adminSelection/adminSideTap.tsx
src/components/ui/header/userInfoHeader.jsx

#206 
- 로그아웃 로직 1차적으로 수정 및 테스트합니다.

(#206)bugfix: 로그아웃 로직 수정합니다.

---

src/components/global/token/tokenManagement.jsx
src/components/pages/termsPage/termsPage.jsx
src/types/event-source-polyfill.d.ts

[Bugfix] 알림 연결 수정했습니다.

---

package.json
src/asset/sass/pages/postPage/questionWritePage.scss
src/components/pages/postPage/questionDetailPage.jsx
src/components/pages/postPage/questionWritePage.tsx
src/components/pages/searchPage/companyInfoPage.jsx
src/components/pages/searchPage/companyRegistPage.tsx
src/components/pages/searchPage/searchResultPage.tsx
src/components/ui/searchInput/searchInput.tsx
src/utils/utils.ts
yarn.lock

- 질문 등록 버튼 안 보이던 문제 수정, 내용 채워질 시 등록 버튼 활성화
- node-sass 관련 문제 해결 중입니다. `yarn.lock` ,  `rm -rf node_modules` -> `yarn install` -> `yarn add node-sass` 까지 실행했을 때 `package.json`에서 node-sass가 추가되지 않는 현상이 발생하고 있는데 계속 확인해보겠습니다.

[UI] UI 수정, node-sass 관련 문제 테스트

---

src/asset/sass/pages/searchPage/companyInfoPage.scss
src/components/ui/question/question.tsx
src/components/ui/toast/toast.tsx

[UI] 기업 상세 페이지 UI 수정

---

src/components/ui/tabBar/tabBar.jsx
src/components/ui/toast/toast.tsx

#213
- 토스트 스타일 변경했습니다.
- 탭 바 내 메뉴 변동되는 오류 수정했습니다.

[Bugfix] 알파테스트 UI 오류 수정

---

src/asset/image/feedback.svg
src/asset/sass/etc/header/sideBar.scss
src/components/global/utils/eventApiUtils.js
src/components/ui/adminSelection/companyDetail.tsx
src/globalStyles.js

[bugfix] 실시간 알림 수정

---

package.json
src/components/pages/myPage/myPage.tsx

[Feature] 마이페이지 CSS 추가

---

src/asset/sass/etc/header/sideBar.scss
src/asset/sass/etc/header/userInfoHeader.scss
src/asset/sass/etc/inputBox/textArea.scss
src/asset/sass/pages/myPage/feedbackPage.scss
src/asset/sass/pages/myPage/myPage.scss
src/components/pages/loginPage/loginPage.tsx
src/components/ui/myPageSelection/myComponent.scss
src/components/ui/tabBar/tabBar.jsx
src/components/ui/tabBar/tabBar.tsx

Feature/#266 alpha UI improvement

---

src/components/pages/searchPage/searchResultPage.tsx
src/components/ui/searchInput/searchInput.tsx

#238 
- 검색 결과 클릭 시 결과 안나오는 에러 해결
- 검색 결과 페이지에서 재 검색 시 결과 수정되지 않는 부분 수정
- 검색 결과에서 뒤로가기 진행 시 오류나는 부분 수정

Bugfix: 클릭 시 검색 안되는 오류 및 검색 후 재검색 로직 수정

---

src/components/pages/searchPage/searchResultPage.tsx
src/components/ui/searchInput/searchInput.tsx

#238 
- 비로그인 시에도 검색 가능하도록 로직 수정.

[Bugfix] 비로그인 시 검색 가능하도록 수정

---

src/components/global/token/tokenManagement.jsx

bugfix 토큰 불러올 때 발생하는 훅 에러 수정합니다.

---

src/components/global/token/tokenManagement.jsx

bugfix 핸들러 function 변경으로 인한 토큰 발급 로직 에러 수정합니다.

---

src/asset/sass/etc/tabBar/tabBar.scss
src/components/global/token/tokenManagement.jsx
src/components/global/utils/eventApiUtils.js

bugfix 실시간 알림 버그 수정

---

src/asset/sass/pages/notificationPage/notificationList.scss
src/asset/sass/pages/notificationPage/notificationPage.scss
src/components/global/utils/eventApiUtils.js
src/components/pages/notificationPage/notificationList.jsx
src/components/pages/notificationPage/notificationPage.jsx

(#195)feat: 실시간 알림 확인 기능 추가합니다.

---

src/asset/sass/etc/tabBar/tabBar.scss
src/components/global/token/tokenManagement.jsx
src/components/ui/tabBar/tabBar.jsx
src/components/ui/tabBar/tabBar.tsx

#195 
실시간 알림 기능 확인을 위한 테스트 로그 추가합니다.

bugfix 실시간 알림 기능 확인을 위한 테스트 로그 추가합니다.

---

src/components/global/token/tokenManagement.jsx

실시간 알림 기능 확인을 위한 테스트 로그 추가합니다.

---

src/components/ui/question/answer.tsx

답변 채택이 되었다는 것을 인지하기 위해 커스텀 토스트 컴포넌트 사용

feat : 답변 채택 인지

---

package.json
src/asset/sass/etc/header/userInfoHeader.scss
src/asset/sass/pages/searchPage/searchResultPage.scss
src/components/global/token/tokenManagement.jsx
src/components/global/utils/eventApiUtils.js
src/components/pages/myPage/myPage.tsx
src/components/pages/premiumPage/NotFound.jsx
src/components/pages/searchPage/searchResultPage.tsx
src/components/pages/termsPage/termsPage.tsx
src/components/ui/adminSelection/adminPagination.tsx
src/components/ui/contactSlider/contactSlider.jsx
src/components/ui/header/userInfoHeader.jsx
src/components/ui/selectSlider/selectSlider.tsx
src/components/ui/tabBar/tabBar.jsx
src/components/ui/tabBar/tabBar.tsx
src/index.css
src/styledComponent.js

#195 
- 실시간 알림 코드 기존 방식으로 원복합니다.
- 페이지네이션 내 파란 드래그 생기는 부분 수정했습니다.
- 로그인 여부에 따라 탭 바의 UI 변경 대신 이동 링크 수정으로 변경했습니다.
- 개발 편의를 위해 devs 스크립트 추가했습니다(프론트엔드 개발 시 package.json 수정 대신, yarn devs로 실행)
- 실시간 알림 화면 연동을 위해 탭바로 코드 이동 예정

bugfix 실시간 알림 코드 수정합니다.

---

src/asset/sass/etc/question/answer.scss
src/asset/sass/pages/postPage/questionDetailPage.scss
src/components/pages/postPage/questionDetailPage.tsx
src/components/ui/Pagination.tsx
src/components/ui/question/answer.tsx
yarn.lock

답변 및 질문 상세 페이지 UI 수정하였습니다.
- 페이지네이션 적용

답변 및 질문 상세 페이지 UI 수정

---

src/asset/sass/etc/header/userInfoHeader.scss
src/asset/sass/pages/mainPage/mainPage.scss
src/asset/sass/pages/myPage/noticePage.scss
src/components/NotFoundPage.tsx
src/components/global/utils/apiUtil.js
src/components/global/utils/eventApiUtils.js
src/components/pages/loginPage/nicknamePage.jsx
src/components/pages/myPage/feedbackPage.tsx
src/components/pages/myPage/infoEditPage.tsx
src/components/pages/myPage/myPage.tsx
src/components/pages/myPage/noticePage.tsx
src/components/pages/myPage/secessionPage.tsx
src/components/pages/notificationPage/notificationList.jsx
src/components/pages/notificationPage/notificationPage.jsx
src/components/pages/postPage/questionDetailPage.tsx
src/components/pages/postPage/questionWritePage.tsx
src/components/pages/searchPage/searchResultPage.tsx
src/components/ui/adminSelection/adminSideTap.tsx
src/components/ui/adminSelection/companyDetail.tsx
src/components/ui/contactSlider/contactSlider.jsx
src/components/ui/header/userInfoHeader.jsx
src/components/ui/myPageSelection/myAnswer.tsx
src/components/ui/myPageSelection/myQuestion.tsx
src/components/ui/question/answer.tsx
src/components/ui/searchInput/searchInput.tsx
src/components/ui/selectSlider/selectSlider.tsx
src/hooks/errorBoundary.tsx
src/router/allRouter.js

#226 
- 검색 페이지 UI 수정
- 검색 결과 페이지 UI  수정
- 공지사항 UI 수정 및 API 연동

공지사항, 공통 UI  수정했습니다.

---

src/asset/sass/etc/header/userInfoHeader.scss
src/asset/sass/pages/mainPage/mainPage.scss
src/asset/sass/pages/myPage/noticePage.scss
src/components/NotFoundPage.tsx
src/components/global/utils/apiUtil.js
src/components/global/utils/eventApiUtils.js
src/components/pages/loginPage/nicknamePage.jsx
src/components/pages/myPage/feedbackPage.tsx
src/components/pages/myPage/infoEditPage.tsx
src/components/pages/myPage/myPage.tsx
src/components/pages/myPage/noticePage.tsx
src/components/pages/myPage/secessionPage.tsx
src/components/pages/notificationPage/notificationList.jsx
src/components/pages/notificationPage/notificationPage.jsx
src/components/pages/postPage/questionDetailPage.tsx
src/components/pages/postPage/questionWritePage.tsx
src/components/pages/searchPage/searchResultPage.tsx
src/components/ui/adminSelection/adminSideTap.tsx
src/components/ui/adminSelection/companyDetail.tsx
src/components/ui/contactSlider/contactSlider.jsx
src/components/ui/header/userInfoHeader.jsx
src/components/ui/myPageSelection/myAnswer.tsx
src/components/ui/myPageSelection/myQuestion.tsx
src/components/ui/question/answer.tsx
src/components/ui/searchInput/searchInput.tsx
src/components/ui/selectSlider/selectSlider.tsx
src/hooks/errorBoundary.tsx
src/router/allRouter.js

Reverts COFLLL/CoverFlow-FE#267

Revert "공지사항, 공통 UI  수정했습니다."

---

src/components/global/token/tokenManagement.jsx
src/components/global/utils/eventApiUtils.js
src/components/pages/notificationPage/notificationList.jsx
src/components/pages/termsPage/termsPage.tsx

#271 
- 실시간 알림 연동, 토스트 연동 테스트입니다.

(#271)bugfix: 실시간 알림 연동 되도록 수정했습니다.

---

src/asset/sass/etc/header/userInfoHeader.scss
src/asset/sass/pages/mainPage/mainPage.scss
src/components/NotFoundPage.tsx
src/components/pages/notificationPage/notificationList.jsx
src/components/ui/selectSlider/selectSlider.tsx
src/hooks/errorBoundary.tsx
src/router/allRouter.js

#271 
로그인 여부에 따른 메인 화면 UI 위치 수정
상점 페이지 탭바 색상 변경 안되는 이슈 수정

[Bugfix] 스타일 수정

---

src/components/global/constants/index.ts
src/components/global/utils/eventApiUtils.js
src/components/pages/notificationPage/notificationList.jsx
src/components/pages/notificationPage/notificationPage.jsx
src/components/pages/searchPage/searchResultPage.tsx
src/components/ui/contactSlider/contactSlider.jsx
src/components/ui/contactSlider/disclaimer.jsx
src/components/ui/myPageSelection/myAnswer.tsx
src/components/ui/myPageSelection/myQuestion.tsx

#271 
- 무한 스크롤 적용했습니다.
[scrnli_2024- 4- 30- 오전 3-13-37.webm](https://github.com/COFLLL/Coverflow-FE/assets/122436452/f7ed85f2-0238-4991-8184-9d3d99d61395)

알림 페이지 무한 스크롤 적용했습니다.

---

src/asset/image/notification-answer.svg
src/asset/image/notification-question.svg
src/asset/sass/pages/myPage/premiumPage.scss
src/asset/sass/pages/notificationPage/notificationList.scss
src/components/global/utils/eventApiUtils.js
src/components/pages/notificationPage/notificationList.jsx
src/components/pages/notificationPage/notificationPage.jsx
src/components/pages/premiumPage/premiumPage.tsx
src/components/pages/premiumPage/premiumTicket.tsx
src/components/ui/banner/bannerImage.scss
src/components/ui/contactSlider/contactList.jsx
src/components/ui/contactSlider/contactList.scss
src/components/ui/contactSlider/contactSlider.jsx

#271 
- 실시간 알림 카운트, 알림 안뜨는 오류 수정
- 실시간 알림 연결 시간 수정
- 실시간 알림 내 이동 로직 수정
- 프리미언 페이지 스타일 수정
- 문의 페이지 스타일 수정

실시간 알림  기능 및 UI 수정했습니다.

---

src/asset/sass/etc/header/userInfoHeader.scss
src/asset/sass/pages/postPage/questionDetailPage.scss
src/components/pages/postPage/questionDetailPage.tsx
src/components/ui/question/answer.tsx

UI 수정 및 로직 수정

---

src/components/global/token/tokenManagement.jsx
src/components/global/utils/apiUtil.js
src/components/global/utils/eventApiUtils.js
src/components/global/utils/reissueTokenUtils.js
src/components/pages/loginPage/nicknamePage.jsx
src/components/pages/myPage/infoEditPage.tsx
src/components/pages/myPage/noticePage.tsx
src/components/pages/notificationPage/notificationList.jsx
src/components/pages/notificationPage/notificationPage.jsx
src/components/pages/searchPage/searchResultPage.tsx
src/components/pages/termsPage/termsPage.tsx
src/components/ui/adminSelection/adminPagination.tsx
src/components/ui/adminSelection/adminSideTap.tsx
src/components/ui/adminSelection/feedbackSelection.tsx
src/components/ui/contactSlider/contactList.jsx
src/components/ui/contactSlider/contactSlider.jsx
src/components/ui/header/userInfoHeader.jsx
src/components/ui/myPageSelection/myAnswer.tsx
src/components/ui/question/answerContainer.jsx

#271 
- 토큰 만료시 재발급 로직 수정 
- 토큰 재발급 핸들러 미적용 함수 수정
- 개정된 약관 주소로 수정

SSE 및 토큰 재발급 로직 수정했습니다.

---

src/components/ui/question/answer.tsx

- 답변 채택 핸들러 실행 시에 api 호출이 가장 먼저 되는 부분을 다시 수정했습니다.

fix : 답변 채택 로직 수정

---

src/App.js
src/asset/image/tabbar-new-alert.svg
src/asset/sass/etc/tabBar/tabBar.scss
src/asset/sass/pages/notificationPage/notificationList.scss
src/components/global/token/tokenManagement.jsx
src/components/global/utils/alertCountUtil.js
src/components/global/utils/eventApiUtils.js
src/components/global/utils/reissueTokenUtils.js
src/components/pages/myPage/feedbackPage.tsx
src/components/pages/notificationPage/notificationList.jsx
src/components/pages/notificationPage/notificationPage.jsx
src/components/pages/termsPage/termsPage.tsx
src/components/ui/header/userInfoHeader.jsx
src/components/ui/myPageSelection/myAnswer.tsx
src/components/ui/myPageSelection/myComponent.scss

UI check list 반영했습니다.

---

src/components/pages/searchPage/companyInfoPage.tsx

style : 기업 상세 구분선 추가

---

src/asset/sass/etc/header/userInfoHeader.scss
src/components/pages/postPage/questionDetailPage.tsx

수정/삭제, 신고 드롭다운 위치 수정

---

src/asset/sass/pages/postPage/questionDetailPage.scss
src/asset/sass/pages/postPage/questionWritePage.scss
src/components/pages/postPage/questionDetailPage.tsx
src/components/pages/postPage/questionWritePage.tsx
src/components/ui/adminSelection/memberSelection.scss
src/components/ui/adminSelection/memberSelection.tsx

답변 input 창,기업상세 타이틀 및 태그 줄바꿈, 버튼 활성화 수정 및 관리자 CSS 네이밍 수정
https://github.com/COFLLL/Coverflow-FE/assets/53456037/a9f0e4c2-8476-46aa-ad3d-0f7a4f283764

답변 input 창,기업상세 타이틀 및 태그 줄바꿈, 버튼 활성화 수정 및 관리자 CSS 네이밍 수정

---

src/asset/image/noContents.svg
src/asset/sass/etc/noContentsComponent/noContentsComponents.scss
src/asset/sass/etc/question/answer.scss
src/asset/sass/etc/question/question.scss
src/asset/sass/etc/selection/fishTag.scss
src/asset/sass/pages/postPage/questionDetailPage.scss
src/asset/sass/pages/postPage/questionWritePage.scss
src/asset/sass/pages/searchPage/companyInfoPage.scss
src/components/pages/postPage/questionDetailPage.tsx
src/components/pages/postPage/questionWritePage.tsx
src/components/pages/searchPage/companyInfoPage.tsx
src/components/ui/adminSelection/adminPagination.tsx
src/components/ui/adminSelection/companySelection.scss
src/components/ui/header/userInfoHeader.jsx
src/components/ui/myPageSelection/myAnswer.tsx
src/components/ui/myPageSelection/myQuestion.tsx
src/components/ui/noContentsComponent/noContentsComponent.tsx
src/components/ui/question/answer.tsx
src/components/ui/question/question.tsx
src/components/ui/selection/fishTag.tsx
src/store/actions/type.js
src/store/actions/userActions.js
src/store/userReducer.js

#285 
- 질문 상세 페이지 UI 수정 및 보완
- 질문 작성 페이지 UI 수정 및 보완
- 기업 상세 페이지 UI 수정 및 보완
- 데이터 없을 시 페이지 추가
[scrnli_2024- 5- 8- 오전 8-30-32.webm](https://github.com/COFLLL/Coverflow-FE/assets/122436452/c3aa5444-337c-4e43-a3aa-b21b35b37b43)
[scrnli_2024- 5- 8- 오전 8-31-20.webm](https://github.com/COFLLL/Coverflow-FE/assets/122436452/b8706d21-c1ef-4250-9864-d2b2137d55f8)
[scrnli_2024- 5- 8- 오전 8-32-21.webm](https://github.com/COFLLL/Coverflow-FE/assets/122436452/47a60b6b-8884-489f-bed0-3ca85197a7b6)

질문 상세 페이지, 질문 작성 페이지, 기업 조회 페이지, 데이터 없을 때 화면 UI 추가

---

src/asset/sass/etc/header/userInfoHeader.scss
src/asset/sass/etc/question/answer.scss
src/asset/sass/etc/question/question.scss
src/asset/sass/pages/postPage/questionDetailPage.scss
src/asset/sass/pages/postPage/questionWritePage.scss
src/asset/sass/pages/storePage/storePage.scss

Fix : UI 수정

---

src/asset/sass/etc/selection/fishTag.scss
src/asset/sass/pages/postPage/questionWritePage.scss
src/components/pages/postPage/questionDetailPage.tsx
src/components/pages/postPage/questionWritePage.tsx
src/components/pages/searchPage/companyInfoPage.tsx
src/components/ui/question/answer.tsx

- questionDetailPage에서 questionWritePage로 이동할 때 state를 넘겨주는 방식을 사용했는데 다른 좋은 방법이 있으면 코멘트 부탁드리겠습니다!
- 신고, 수정/삭제 모달은 계속 수정 중입니다.
- 질문 수정 시 나오는 토스트 메시지는 추후에 적절하게 수정하겠습니다.
https://github.com/COFLLL/Coverflow-FE/assets/88266129/d83b3f0a-02b0-4a71-8e1d-f373969d8d56

질문 수정 기능 추가, UI 수정

---

src/asset/sass/etc/header/userInfoHeader.scss
src/asset/sass/pages/postPage/questionDetailPage.scss
src/components/pages/postPage/questionDetailPage.tsx
src/components/pages/postPage/questionWritePage.tsx

#285 
- 붕어빵 외 영역 호버 표시 삭제
- 답변 작성 시 placeholder 내용 수정

UI check list 적용

---

src/asset/sass/etc/header/userInfoHeader.scss
src/asset/sass/pages/postPage/questionWritePage.scss
src/components/pages/postPage/questionWritePage.tsx
src/components/ui/question/answer.tsx

- 클래스네임 변경을 통해 신고, 수정/삭제 모달 위치 수정
- 질문 작성 페이지 UI 수정

질문 상세, 질문 작성 페이지 수정

---

src/components/pages/postPage/questionDetailPage.tsx

#285 
- 질문 상세 페이지 내 답변이 있을 경우 토스트 발생하도록 수정

질문 상세 페이지 답변 삭제, 수정 로직 추가했습니다.

---

src/components/global/constants/index.ts

(24/05/10 - 2) 클로즈 베타 테스트 버전 배포합니다.

(24/05/10 - 2) 클로즈 베타 테스트 버전 배포합니다.

---

src/components/pages/postPage/questionDetailPage.tsx
src/components/pages/searchPage/searchResultPage.tsx
src/components/ui/question/answer.tsx

필요없는 코드 제거

---

src/components/ui/adminSelection/companySelection.tsx
src/components/ui/adminSelection/memberSelection.tsx

console.log 제거

---

src/components/global/token/tokenManagement.jsx

회원가입 시 약관동의 페이지로 안 가는 부분 수정 중

---

src/components/global/token/tokenManagement.jsx

fix : 분기 처리 로직 수정 작업 중

---

src/components/global/token/tokenManagement.jsx

최초 가입 시 토큰 발행 로직 수정했습니다.

---

src/components/pages/termsPage/termsPage.tsx

약관 동의 페이지 코드 로직 수정

---

src/components/global/token/tokenManagement.jsx

약관 동의 페이지 코드 받는 로직 수정

---

src/components/pages/loginPage/nicknamePage.jsx

#285 
- 정보 입력 페이지 post 요청 endpoint 수정

정보 입력 페이지 post 요청 수정했습니다.

---

src/components/global/token/tokenManagement.jsx
src/components/pages/myPage/secessionPage.tsx
src/components/pages/termsPage/termsPage.tsx

탈퇴 로직 수정했습니다.

---

src/components/pages/searchPage/companyRegistPage.tsx

비회원 상태일 때 기업 등록 안되는 부분 수정

---

src/components/global/utils/apiUtil.js
src/components/pages/postPage/questionDetailPage.tsx
src/components/pages/searchPage/companyInfoPage.tsx
src/components/pages/searchPage/companyRegistPage.tsx

질문 태그 선택 취소 시 전체 질문 리스트 안 보이는 부분 수정
각자 로컬에서 제대로 반영됐는 지 확인해주세요!

 질문 리스트 버그 수정

---

src/asset/sass/pages/myPage/noticePage.scss
src/asset/sass/pages/storePage/storePage.scss
src/components/global/token/tokenManagement.jsx
src/components/global/utils/alertCountUtil.js
src/components/global/utils/eventApiUtils.js
src/components/global/utils/reissueTokenUtils.js
src/components/pages/loginPage/nicknamePage.jsx
src/components/pages/myPage/feedbackPage.tsx
src/components/pages/myPage/infoEditPage.tsx
src/components/pages/myPage/myPage.tsx
src/components/pages/myPage/noticePage.tsx
src/components/pages/notificationPage/notificationList.jsx
src/components/pages/storePage/storePage.tsx
src/components/pages/termsPage/termsPage.tsx
src/components/ui/contactSlider/contactSlider.jsx
src/components/ui/header/userInfoHeader.jsx
src/components/ui/myPageSelection/myAnswer.tsx
src/components/ui/question/answerContainer.jsx

#329 
- 공지사항 UI 수정
- 상점 방문 시 에러 토스트
- 로그인 실패시 홈으로 이동
- 약관 선택 동의 옵션 추가

베타 테스트 중 발생 에러 수정 및 기능 변경

---

src/asset/sass/pages/myPage/noticePage.scss
src/asset/sass/pages/storePage/storePage.scss
src/components/global/constants/index.ts
src/components/global/token/tokenManagement.jsx
src/components/global/utils/alertCountUtil.js
src/components/global/utils/apiUtil.js
src/components/global/utils/eventApiUtils.js
src/components/global/utils/reissueTokenUtils.js
src/components/pages/loginPage/nicknamePage.jsx
src/components/pages/myPage/feedbackPage.tsx
src/components/pages/myPage/infoEditPage.tsx
src/components/pages/myPage/myPage.tsx
src/components/pages/myPage/noticePage.tsx
src/components/pages/myPage/secessionPage.tsx
src/components/pages/notificationPage/notificationList.jsx
src/components/pages/postPage/questionDetailPage.tsx
src/components/pages/searchPage/companyInfoPage.tsx
src/components/pages/searchPage/companyRegistPage.tsx
src/components/pages/storePage/storePage.tsx
src/components/pages/termsPage/termsPage.tsx
src/components/ui/contactSlider/contactSlider.jsx
src/components/ui/header/userInfoHeader.jsx
src/components/ui/myPageSelection/myAnswer.tsx
src/components/ui/question/answerContainer.jsx

(24/05/14 - 1) 클로즈 베타 테스트 버전 배포합니다.

(24/05/14 - 1) 클로즈 베타 테스트 버전 배포합니다.

---

src/asset/sass/pages/myPage/infoEditPage.scss
src/asset/sass/pages/myPage/noticePage.scss
src/components/pages/myPage/feedbackPage.tsx
src/components/pages/myPage/infoEditPage.tsx
src/components/pages/myPage/noticePage.tsx
src/components/ui/contactSlider/contactList.scss
src/components/ui/contactSlider/contactSlider.jsx
src/components/ui/header/userInfoHeader.jsx

#329 
- 공지사항 줄바꿈 적용
- 문의사항 탭 길이 수정
- 피드백 페이지 길이에 따른 제한 추가
- 상점 페이지 이동 제한
- 닉네임 변경 디스클레이머 추가

UI 개선 사항 적용

---

src/components/ui/searchInput/searchInput.tsx

Input 창에 적용되어있는 키 입력 이벤트를 수정했습니다.

검색어 입력 버그 수정

---

src/components/pages/myPage/noticePage.tsx
src/components/pages/postPage/questionDetailPage.tsx
src/components/ui/question/answer.tsx

채택 표시 여부 로직 수정했습니다.
